plugins {
    id 'java'
}

base {
    archivesName = 'wallcanvas-paper'
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_api_version}"
    implementation project(':wallcanvas-core')
    implementation 'org.sejda.imageio:webp-imageio:0.1.6'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('plugin.yml') {
        expand 'version': project.version
    }
}

jar {
    from(project(':wallcanvas-core').sourceSets.main.output)
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath
                .filter { it.name.contains('webp-imageio') }
                .collect { zipTree(it) }
    }
}
