plugins {
    id 'java'
}

group = project.maven_group
gversion = project.mod_version

subprojects {
    apply plugin: 'java-library'

    group = rootProject.maven_group
    version = rootProject.mod_version

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
    }

    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }
}

project(':wallcanvas-core') {
    dependencies {
        api 'com.google.code.gson:gson:2.13.1'
    }
}
