pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    // Fabric Loom adds repositories at project level for its generated mappings.
    // Allow those repositories to participate in dependency resolution.
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }
}

rootProject.name = 'WallCanvas'
include ':wallcanvas-core', ':wallcanvas-fabric', ':wallcanvas-paper'
